name: Build and Deploy Gytrash CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pypa/build
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute version script # run the run.py to get the latest data
        run: |
          export CURRENT_VERSION=$(python setup.py --version)
          bump2version --current-version $CURRENT_VERSION patch setup.py
          export CURRENT_VERSION=$(python setup.py --version)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
      - name: Build package and wheel
        run: |
          pip install build
          python -m build --sdist --wheel --outdir dist/ .
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: setup.py
          commit-msg: Bumped version to ${{ env.CURRENT_VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.CURRENT_VERSION }}
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.GYTRASH_PYPI_API_TOKEN }}
