# This workflow will install dependencies, create coverage tests and run Pytest Coverage Commentator
# For more information see: https://github.com/coroo/pytest-coverage-commentator
name: test-build-pytest-coverage-commentator-PR-synchronize
on:
  pull_request:
    types:
      - synchronize
    branches: 
      - 'release/**'
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      PR_NUMBER: ${{ github.event.number }}
      PR_TEST: "Test"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install pypa/build
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: execute version script # run the run.py to get the latest data
        run: |
          if ["$PR_NUMBER" != ""]; then export PR_NUMBER=999999; fi
          # Just bump the build number.
          bump2version post
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bumped version to ${{ env.CURRENT_VERSION }}
      - name: Build package and wheel
        run: |
          pip install build
          pip install wheel
          python -m build -n --sdist --wheel --outdir dist/ .
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
      - name: Build coverage file
        run: |
          pytest --cache-clear --cov=gytrash test/ > pytest-coverage.txt
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2